version: '3.8'

services:
  # Сервер бэкенда (Django)
  backend:
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Здесь можно указать настройки подключения к БД, если используете не SQLite

  # Сервер фронтенда (React/Vue/Vite)
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
