# Generated by Django 6.1.1 on 2026-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст совета для игрока')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
